# Generated by Django 5.2.8 on 2025-11-20 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workinghours",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialty",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.specialty"
            ),
        ),
        migrations.RemoveField(
            model_name="workinghours",
            name="owner",
        ),
    ]
