# Generated by Django 5.2.8 on 2025-11-20 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_workinghours_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="specialty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.specialty"
            ),
        ),
    ]
