# Generated by Django 5.2.8 on 2025-11-26 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_doctor_specialty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="working_hours",
        ),
        migrations.AddField(
            model_name="workinghours",
            name="doctor",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="working_hours",
                to="api.doctor",
            ),
            preserve_default=False,
        ),
    ]
