# Generated by Django 5.2.8 on 2025-11-26 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_doctor_working_hours_workinghours_doctor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workinghours",
            name="doctor",
        ),
    ]
