# Generated by Django 5.2.8 on 2025-11-26 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_workinghours_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="workinghours",
            name="doctor",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="working_hours",
                to="api.doctor",
            ),
            preserve_default=False,
        ),
    ]
