# Generated by Django 5.2.8 on 2025-11-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_workinghours_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="appointment_duration",
            field=models.PositiveIntegerField(
                default=30, help_text="Длительность приема в минутах"
            ),
        ),
        migrations.AddField(
            model_name="workinghours",
            name="before_lunch",
            field=models.BooleanField(default=True),
        ),
    ]
