# Generated by Django 5.2.8 on 2025-12-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_doctor_appointment_duration_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workinghours",
            unique_together={("day_of_week", "before_lunch", "doctor")},
        ),
    ]
